const counties = [
    "Blekinge län",
    "Bottenhavet",
    "Bottenviken",
    "Bälten",
    "Dalarnas län",
    "Finska viken",
    "Gotlands län",
    "Gävleborgs län",
    "Hallands län",
    "Jämtlands län",
    "Jönköpings län",
    "Kalmar län",
    "Kattegatt",
    "Kronobergs län",
    "Norra Kvarken",
    "Norrbottens län",
    "Rigabukten",
    "Skagerack",
    "Skärgårdshavet",
    "Skåne län",
    "Stockholms län",
    "Södermanlands län",
    "Uppsala län",
    "Vänern",
    "Värmlands län",
    "Västerbottens län",
    "Västernorrlands län",
    "Västmanlands län",
    "Västra Götalands län",
    "Ålands hav",
    "Örebro län",
    "Öresund",
    "Östergötlands län",
    "Östersjön",
]

export default counties
