const counties = [
    "Blekinge län",
    "Bottenviken",
    "Bälten",
    "Dalarnas län utom Dalafjällen",
    "Dalarnas län, Dalafjällen",
    "Finska viken",
    "Gotlands län",
    "Gävleborgs län inland",
    "Gävleborgs län kustland",
    "Hallands län",
    "Jämtlands län utom fjällen",
    "Jämtlands län, Härjedalsfjällen",
    "Jämtlands län, Jämtlandsfjällen",
    "Jönköpings län, syd om Vättern",
    "Jönköpings län, västra delen utom syd om Vättern",
    "Jönköpings län, östra delen",
    "Kalmar län utom Öland",
    "Kalmar län, Öland",
    "Kattegatt",
    "Kronobergs län, västra delen",
    "Kronobergs län, östra delen",
    "Mellersta Östersjön",
    "Norra Bottenhavet",
    "Norra Kvarken",
    "Norra Östersjön",
    "Norrbottens län, inland",
    "Norrbottens län, kustland",
    "Norrbottens län, norra Lapplandsfjällen",
    "Rigabukten",
    "Skagerack",
    "Skärgårdshavet",
    "Skåne län utom Österlen",
    "Skåne län, Österlen",
    "Stockholms län utom Roslagskusten",
    "Stockholms län, Roslagskusten",
    "Sydvästra Östersjön",
    "Sydöstra Östersjön",
    "Södermanlands län",
    "Södra Bottenhavet",
    "Södra Östersjön",
    "Uppsala län, utom Upplandskusten",
    "Uppsala län, Upplandskusten",
    "Vänern",
    "Värmlands län",
    "Västerbottens län inland",
    "Västerbottens län kustland",
    "Västerbottens län, södra Lapplandsfjällen",
    "Västernorrlands län",
    "Västmanlands län",
    "Västra Götalands län, Bohuslän och Göteborg",
    "Västra Götalands län, inre Dalsland",
    "Västra Götalands län, norra Västergötland",
    "Västra Götalands län, Sjuhäradsbygden och Göta älv",
    "Västra Götalands län, sydväst Vänern",
    "Ålands hav",
    "Örebro län",
    "Öresund",
    "Östergötlands län",
]

/*function getCounties(){
    return this.counties;
}*/

export default counties
