const counties = [
    { name: "Blekinge län" },
    { name: "Bottenviken" },
    { name: "Bälten" },
    { name: "Dalarnas län utom Dalafjällen" },
    { name: "Dalarnas län, Dalafjällen" },
    { name: "Finska viken" },
    { name: "Gotlands län" },
    { name: "Gävleborgs län inland" },
    { name: "Gävleborgs län kustland" },
    { name: "Hallands län" },
    { name: "Jämtlands län utom fjällen" },
    { name: "Jämtlands län, Härjedalsfjällen" },
    { name: "Jämtlands län, Jämtlandsfjällen" },
    { name: "Jönköpings län, syd om Vättern" },
    { name: "Jönköpings län, västra delen utom syd om Vättern" },
    { name: "Jönköpings län, östra delen" },
    { name: "Kalmar län utom Öland" },
    { name: "Kalmar län, Öland" },
    { name: "Kattegatt" },
    { name: "Kronobergs län, västra delen" },
    { name: "Kronobergs län, östra delen" },
    { name: "Mellersta Östersjön" },
    { name: "Norra Bottenhavet" },
    { name: "Norra Kvarken" },
    { name: "Norra Östersjön" },
    { name: "Norrbottens län, inland" },
    { name: "Norrbottens län, kustland" },
    { name: "Norrbottens län, norra Lapplandsfjällen" },
    { name: "Rigabukten" },
    { name: "Skagerack" },
    { name: "Skärgårdshavet" },
    { name: "Skåne län utom Österlen" },
    { name: "Skåne län, Österlen" },
    { name: "Stockholms län utom Roslagskusten" },
    { name: "Stockholms län, Roslagskusten" },
    { name: "Sydvästra Östersjön" },
    { name: "Sydöstra Östersjön" },
    { name: "Södermanlands län" },
    { name: "Södra Bottenhavet" },
    { name: "Södra Östersjön" },
    { name: "Uppsala län, utom Upplandskusten" },
    { name: "Uppsala län, Upplandskusten" },
    { name: "Vänern" },
    { name: "Värmlands län" },
    { name: "Västerbottens län inland" },
    { name: "Västerbottens län kustland" },
    { name: "Västerbottens län, södra Lapplandsfjällen" },
    { name: "Västernorrlands län" },
    { name: "Västmanlands län" },
    { name: "Västra Götalands län, Bohuslän och Göteborg" },
    { name: "Västra Götalands län, inre Dalsland" },
    { name: "Västra Götalands län, norra Västergötland" },
    { name: "Västra Götalands län, Sjuhäradsbygden och Göta älv" },
    { name: "Västra Götalands län, sydväst Vänern" },
    { name: "Ålands hav" },
    { name: "Örebro län" },
    { name: "Öresund" },
    { name: "Östergötlands län" },
]

/*function getCounties(){
    return this.counties;
}*/

export default counties
