const counties = [
    { name: "Blekinge län", id: 1 },
    { name: "Bottenviken", id: 2 },
    { name: "Bälten", id: 3 },
    { name: "Dalarnas län utom Dalafjällen", id: 4 },
    { name: "Dalarnas län, Dalafjällen", id: 5 },
    { name: "Finska viken", id: 6 },
    { name: "Gotlands län", id: 7 },
    { name: "Gävleborgs län inland", id: 8 },
    { name: "Gävleborgs län kustland", id: 9 },
    { name: "Hallands län", id: 10 },
    { name: "Jämtlands län utom fjällen", id: 11 },
    { name: "Jämtlands län, Härjedalsfjällen", id: 12 },
    { name: "Jämtlands län, Jämtlandsfjällen", id: 13 },
    { name: "Jönköpings län, syd om Vättern", id: 14 },
    { name: "Jönköpings län, västra delen utom syd om Vättern", id: 15 },
    { name: "Jönköpings län, östra delen", id: 16 },
    { name: "Kalmar län utom Öland", id: 17 },
    { name: "Kalmar län, Öland", id: 18 },
    { name: "Kattegatt", id: 19 },
    { name: "Kronobergs län, västra delen", id: 20 },
    { name: "Kronobergs län, östra delen", id: 21 },
    { name: "Mellersta Östersjön", id: 22 },
    { name: "Norra Bottenhavet", id: 23 },
    { name: "Norra Kvarken", id: 24 },
    { name: "Norra Östersjön", id: 25 },
    { name: "Norrbottens län, inland", id: 26 },
    { name: "Norrbottens län, kustland", id: 27 },
    { name: "Norrbottens län, norra Lapplandsfjällen", id: 28 },
    { name: "Rigabukten", id: 29 },
    { name: "Skagerack", id: 30 },
    { name: "Skärgårdshavet", id: 31 },
    { name: "Skåne län utom Österlen", id: 32 },
    { name: "Skåne län, Österlen", id: 33 },
    { name: "Stockholms län utom Roslagskusten", id: 34 },
    { name: "Stockholms län, Roslagskusten", id: 35 },
    { name: "Sydvästra Östersjön", id: 36 },
    { name: "Sydöstra Östersjön", id: 37 },
    { name: "Södermanlands län", id: 38 },
    { name: "Södra Bottenhavet", id: 39 },
    { name: "Södra Östersjön", id: 40 },
    { name: "Uppsala län, utom Upplandskusten", id: 41 },
    { name: "Uppsala län, Upplandskusten", id: 42 },
    { name: "Vänern", id: 43 },
    { name: "Värmlands län", id: 44 },
    { name: "Västerbottens län inland", id: 45 },
    { name: "Västerbottens län kustland", id: 46 },
    { name: "Västerbottens län, södra Lapplandsfjällen", id: 47 },
    { name: "Västernorrlands län", id: 48 },
    { name: "Västmanlands län", id: 49 },
    { name: "Västra Götalands län, Bohuslän och Göteborg", id: 50 },
    { name: "Västra Götalands län, inre Dalsland", id: 51 },
    { name: "Västra Götalands län, norra Västergötland", id: 52 },
    { name: "Västra Götalands län, Sjuhäradsbygden och Göta älv", id: 53 },
    { name: "Västra Götalands län, sydväst Vänern", id: 54 },
    { name: "Ålands hav", id: 55 },
    { name: "Örebro län", id: 56 },
    { name: "Öresund", id: 57 },
    { name: "Östergötlands län", id: 58 },
]

/*function getCounties(){
    return this.counties;
}*/

export default counties